idf_component_register(
    SRCS
        "buttons.c"
        "buzzer.c"
        "dht.c"
        "hcsro4.c"
        "mpu6050.c"
        "mq2.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_i2c
        esp_timer
        esp_adc
        log
)